##  SPDX-License-Identifier: BSD-3-Clause
##  Copyright (c) 2023, Sören Jakob Gerke

## given the set of parameters pp is unique, return the index in ltab
##
## Author: Sören J. Gerke
##

function idx_measid = get_measidx (ltab, head, pp)
  idx_measid = 0;
  idx = ...
  ismember (ltab(2:end,get_col (head,pp.type.id(:))), pp.type.data) == 1     & ...
  ismember (ltab(2:end,get_col (head,pp.cell.id(:))), pp.cell.data) == 1     & ...
  strncmp (ltab(2:end,get_col (head,pp.optset.id)), pp.optset.data, 3)       & ...
  cell2mat (ltab(2:end,get_col (head,pp.alpha.id(:)))) == pp.alpha.data      & ...
  cell2mat (ltab(2:end,get_col (head,pp.T.id(:)))) == pp.T.data              & ...
  ismember (ltab(2:end,get_col (head,pp.liquid.id(:))), pp.liquid.data) == 1 & ...
  cell2mat (ltab(2:end,get_col (head,pp.M.id(:)))) == pp.M.data              & ...
  cell2mat (ltab(2:end,get_col (head,pp.G.id(:)))) == pp.G.data              & ...
  cell2mat (ltab(2:end,get_col (head,pp.X.id(:)))) == pp.X.data              & ...
  cell2mat (ltab(2:end,get_col (head,pp.Z.id(:)))) == pp.Z.data;
  idxx = 1 + find (idx==1);
  if ! (numel (idxx) == 1)
    error (["measid not unique or not existent N = " num2str(numel (idxx))]);
  else
    idx_measid = idxx;
  endif
endfunction
